### ISSUE TITLE
Error: Duplicate data property in object literal not allowed

### ISSUE THREAD

**Issue by kuraga** [facebook/jstransform#99]
What's my next step?
```javascript
let name = 'toy';
let obj = {
  name: name,
  [name]: 1
};
```
```
JsxTransformError: file.jsx: Parse Error: Line 4: Duplicate data property in object literal not allowed in strict mode while parsing file: file.jsx
    at throwError (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2825:24)
    at parseObjectInitialiser (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3399:29)
    at parsePrimaryExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3553:20)
    at parseLeftHandSideExpressionAllowCall (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3656:61)
    at parsePostfixExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3696:20)
    at parseUnaryExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3763:16)
    at parseBinaryExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3853:16)
    at parseConditionalExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3913:16)
    at parseAssignmentExpression (node_modules/jsx-transform/node_modules/jstransform/node_modules/esprima-fb/esprima.js:4166:16)
```

**Comment by zpao** [comment]
I think we fixed this in the latest jstransform. See if upgrading jstransform in the `jsx-transform` package fixes it.

**Comment by kuraga** [comment]
No.
```
jsx-transform@1.2.1 node_modules/jsx-transform
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── jstransform@10.1.0 (base62@0.1.1, source-map@0.1.31, esprima-fb@13001.1001.0-dev-harmony-fb)
```

**Comment by zpao** [comment]
Right, it's using jstransform v10. I think it's fixed in jstransform v11.

**Comment by kuraga** [comment]
Ok, I'll reopen if neccessary.

**Comment by kuraga** [comment]
@zpao No.
```
jsx-transform@2.0.0 node_modules/jsx-transform
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── jstransform@11.0.0 (object-assign@2.0.0, base62@1.1.0, esprima-fb@15001.1.0-dev-harmony-fb, source-map@0.4.2, commoner@0.10.1)
```

**Comment by kuraga** [comment]
@zpao ping

**Comment by zpao** [comment]
This works for me (even if the generated code is ugly as sin). With your code on my clipboard…

```
% pbpaste | jstransform --harmony
built Module("<stdin>")
var $__0;let name = 'toy';
let obj = ($__0={},$__0.name=
   name,$__0[
  name]= 1
,$__0)
```

**Comment by kuraga** [comment]
Sorry, I was impatient somewhere
